Title: Module 5 exercises
Author: Dr. Glasbrenner
Date: 2019-03-25 23:59
Tags: module-exercise
Slug: module05-exercises
Summary: For this module exercise, you will answer a series of questions that check your understanding of the material covered in the Module 5 lectures.
Show_summary: true
Show_link: true

[**Due:** March 25, 2019 @ 11:59pm]{.h3}

## Instructions

This module exercise is a series of questions **posted on Blackboard** that check your understanding of the [module 5 lecture material][module05-lectures] (the in-class lecture on February 28).
You can go directly to the module exercise on Blackboard by [clicking here][blackboard-module-exercises].

::::: {.callout .primary}
There is no time limit and you may attempt the module exercises up to three times.
Your grade will be the highest score you receive across your attempts.
:::::

[module05-lectures]:           /materials/module05-materials/
[blackboard-module-exercises]: https://mymasonportal.gmu.edu/webapps/blackboard/content/listContent.jsp?course_id=_359486_1&content_id=_8969474_1
